<?php
$tradeData = [
  'electrician' => [
    'name' => 'Electrician',
    'duration' => '2 Years',
    'seats' => '48',
    'eligibility' => '10th pass with Science & Math',
    'syllabus' => 'Electrical wiring, industrial safety, motors, transformers, control panels.',
    'career' => 'Electrician, Maintenance Technician, Power Distribution Assistant.',
  ],
  'fitter' => [
    'name' => 'Fitter',
    'duration' => '2 Years',
    'seats' => '48',
    'eligibility' => '10th pass with Science & Math',
    'syllabus' => 'Fitting tools, fabrication, machining, measurement, assembly practices.',
    'career' => 'Fitter, Fabrication Technician, Shop Floor Supervisor.',
  ],
  'welder' => [
    'name' => 'Welder',
    'duration' => '1 Year',
    'seats' => '32',
    'eligibility' => '8th pass',
    'syllabus' => 'Gas welding, arc welding, TIG/MIG basics, safety standards.',
    'career' => 'Welder, Fabricator, Maintenance Assistant.',
  ],
  'turner' => [
    'name' => 'Turner',
    'duration' => '2 Years',
    'seats' => '32',
    'eligibility' => '10th pass with Science & Math',
    'syllabus' => 'Lathe operations, tooling, measurement, CNC basics.',
    'career' => 'Turner, CNC Operator, Tool Room Assistant.',
  ],
  'mechanic-diesel' => [
    'name' => 'Mechanic Diesel',
    'duration' => '1 Year',
    'seats' => '24',
    'eligibility' => '10th pass',
    'syllabus' => 'Diesel engine overhaul, fuel systems, diagnostics, servicing.',
    'career' => 'Diesel Mechanic, Service Advisor, Workshop Assistant.',
  ],
  'copa' => [
    'name' => 'COPA (Computer Operator & Programming Assistant)',
    'duration' => '1 Year',
    'seats' => '48',
    'eligibility' => '10th pass',
    'syllabus' => 'Office automation, basic programming, networking, data entry.',
    'career' => 'Computer Operator, Office Assistant, Data Analyst (Entry Level).',
  ],
  'plumber' => [
    'name' => 'Plumber',
    'duration' => '1 Year',
    'seats' => '24',
    'eligibility' => '8th pass',
    'syllabus' => 'Plumbing tools, fitting, sanitary systems, safety practices.',
    'career' => 'Plumber, Maintenance Technician, Site Supervisor.',
  ],
  'draughtsman' => [
    'name' => 'Draughtsman (Civil)',
    'duration' => '2 Years',
    'seats' => '24',
    'eligibility' => '10th pass with Science & Math',
    'syllabus' => 'AutoCAD, building drawings, estimation, surveying basics.',
    'career' => 'Draughtsman, CAD Technician, Site Planner.',
  ],
];
